### ISSUE TITLE
Non-default Actor

### ISSUE THREAD

**Issue by enzious** [actix/sockjs#4]
On this line here:
https://github.com/actix/sockjs/blob/master/examples/chat.rs#L54

What is the correct way to create a non-default Actor/etc that isn't generated from Default::default()?

**Comment by fafhrd91** [comment]
It is actix api. You can use start https://actix.github.io/actix/actix/trait.Actor.html#method.start or https://actix.github.io/actix/actix/trait.Actor.html#method.create

**Comment by enzious** [comment]
I need to use the SockJSManager though. How do I initiate the actor into the SockJSManager?

**Comment by fafhrd91** [comment]
I see, it is not possible at the moment. I guess we need something like "SessionFactory" trait. I'll add it tomorrow.

if you'd like you can do this yourself, I can give you access to repo.

**Comment by enzious** [comment]
I'll have to look at it for a while. Not quite an expert in Rust yet :/

**Comment by fafhrd91** [comment]
Np, I’ll take a look

**Comment by enzious** [comment]
I'm currently looking into it as well, for learning. What do you think the syntax for supplying the Actor to SockJSManager should look like? So I can have somewhere to start.

**Comment by fafhrd91** [comment]
I think we need `SessionFactory` or `NewSession`, something like:

```rust

trait SessionFactory {
    type Session: Session;

    fn create() -> Self::Session;
}
```

then `SockJSManager` should accept factory:

```rust
/// Session manager
pub struct SockJSManager<F: SessionFactory> {
    factory: F,
    idle: HashSet<Arc<String>>,
    sessions: HashMap<Arc<String>, Entry<F::Session>>,
}

impl<F> SockJSManager<F {
   fn new(factory: F) -> Self {
      SockJSManager {
          factory: factory,
          ...
      }
   }
}
```

then replace all `<S as Default>::default` with `self.factory.create()`

does it make sense?

**Comment by enzious** [comment]
Ah! Yeah! I'll try that out as soon as I'm out of the office.

**Comment by enzious** [comment]
Got stuck here... I might have taken a wrong turn

![selection_008](https://user-images.githubusercontent.com/4645608/33696287-2e7b39fa-dac7-11e7-90ee-4b9624a55c19.png)

**Comment by fafhrd91** [comment]
Fork repo, push your changes and I’ll check

**Comment by enzious** [comment]
https://github.com/enzious/sockjs

**Comment by fafhrd91** [comment]
you added new type parameter `B` which is Session factory, but `Session` is an `Actor` 
so instead of `A: Actor<Context=SockJSContext<A, B>> + Session`
you should use `B::Session: Actor<Context=SockJSContext<B>> + Session`
we don't need `A` any because SessionFactory already has associated type for session type,

**Comment by enzious** [comment]
Feel closer, still having problems with this trait.

![image](https://user-images.githubusercontent.com/4645608/33698008-748f0c3e-dacf-11e7-90c0-5ff835dc10aa.png)

**Comment by fafhrd91** [comment]
try

```rust
pub trait SessionFactory: 'static {
    type Session: Session + 'static;
    fn create() -> Self::Session;
}
```

**Comment by enzious** [comment]
I am stuck here because I don't think you can put a trait (SessionFactory) in a trait method argument, right?

![image](https://user-images.githubusercontent.com/4645608/33698449-324c1878-dad2-11e7-9023-f7ec19ae65df.png)

**Comment by fafhrd91** [comment]
for methods you can use `ctx: &mut <Self as Actor>::Context>`

**Comment by enzious** [comment]
I think I'm 90% there. 
![image](https://user-images.githubusercontent.com/4645608/33699081-7d2b96a8-dad6-11e7-84e9-ba77ed9e4823.png)

**Comment by fafhrd91** [comment]
`B::Session` constraint is recursive, try: `B::Session: Actor<Context=Self> + Session`

**Comment by enzious** [comment]
Says that Self can only be used in traits and impls

**Comment by fafhrd91** [comment]
commit your changes, ill check

**Comment by enzious** [comment]
Pushed them.

**Comment by fafhrd91** [comment]
ok, seems this method doesn't work.

here is another option:

```rust
pub trait SessionFactory<A>: 'static {
    fn create(&self) -> A;
}
pub struct SockJSManager<S: Session> {
    factory: SessionFactory<S>,
    idle: HashSet<Arc<String>>,
    sessions: HashMap<Arc<String>, Entry<S>>,
}
```
this approach should be simpler, it does not need to associate SessionFacrtory and Session

**Comment by enzious** [comment]
I think I got it working. I'll test it in a bit.

**Comment by fafhrd91** [comment]
Awesome

**Comment by enzious** [comment]
Has the route_handler(Handler<>) method been deprecated?

**Comment by fafhrd91** [comment]
I suggest just to replace "default" and stay on actix-web on 0.2 version.

actix-web 0.3 is still in development, but if you'd like to upgrade sockjs to actix-web 0.3, it should be separate PR

**Comment by enzious** [comment]
Oh, I just switched to 0.2 and am not default and it works so 👍

**Comment by enzious** [comment]
What do you think is the best way to share a struct (that contains a connection list, mysql db, etc) between different sessions/clients?

**Comment by fafhrd91** [comment]
Rc<State> should work. I use this approach in actix-web

**Comment by enzious** [comment]
Doesn't that need a RefCell to be mutable?

Also, does this make sense as a function for SockJSContext:
https://github.com/enzious/sockjs/commit/0102f8665dc61797232711606ad05de2afd2ade2

**Comment by fafhrd91** [comment]
1. If you want to share mutable state, then you have to implement it properly. usually connectors do not require mut. other option could be separate actor with specific state, so you use message like "give me db connection" and response could contain connection, but I never explored this approach.

2. why do you send to send session message? those could be different, (reconnection, etc)

**Comment by enzious** [comment]
1. Basically, in a shared mutable space, I want to keep a list of channels.
2. I want to send a message to users in specific channels etc.

**Comment by fafhrd91** [comment]
1. you have to manage mutable space yourself. there are options.

2. why can't you just send "Message", because "SessionMessage" is internal details

**Comment by enzious** [comment]
So if I have a list of Sessions, how do I identify a user/session and send them a message from another session's handler?

**Comment by fafhrd91** [comment]
oh, actually you are right. your change is good.

**Comment by enzious** [comment]
Why is sid an Arc?

**Comment by fafhrd91** [comment]
This is sockjs client I’d. Arc probably is not good idea here and should be removed

**Comment by fafhrd91** [comment]
I am planing to migration sockjs to latest actix-web. are you planing to submit PR for client session factory? I can just implement it during migration

**Comment by fafhrd91** [comment]
implemented
